### ISSUE TITLE
Overview Page : Loan Offers Section

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#15]
Issue : 
If the user clicks on any of the categories like "Credit Card", "Personal Loan", "Business Loan" Etc... 
The user should be redirected to the Offers page with the respective tab as active. 

Example 
If the User clicks on Credit Card div (Screenshot 1) , it should redirect to Offers Page with Credit card tab as active (Screenshot 2)

**Screenshot 1**
<img width="261" alt="Screenshot 2022-09-26 at 3 33 07 PM" src="https://user-images.githubusercontent.com/81156455/192249508-3dcbf426-8dac-41bd-b8a9-d86df941deb3.png">

**Screenshot 2**
![Screenshot 2022-09-26 at 3 33 56 PM](https://user-images.githubusercontent.com/81156455/192249709-4bf3f2cf-a24d-48d9-b1ce-dddd98dc9d8f.png)

**Comment by MamataNivajekar** [comment]
@saieshv The "loan Offers" page is not yet developed.

**Comment by saieshv** [comment]
@MamataNivajekar Can you check this issue.

**Comment by saieshv** [comment]
yes, links are working,
Just need to change Cursor Property to "Pointer" hand like Icon

**Comment by saieshv** [comment]
Hi Mamata, only on 
"Loan against property" & "Auto" 

Clicks are not happening.

**Comment by MamataNivajekar** [comment]
@saieshv fixed the above issue, please check in incognito.
