### ISSUE TITLE
Overview Page : Loan Offers Section

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#16]
On click on "Edit information" CTA (Screenshot 1) User should be redirected to the edit information page (Screenshot 2)
**Screenshot 1**
<img width="481" alt="Screenshot 2022-09-26 at 3 39 28 PM" src="https://user-images.githubusercontent.com/81156455/192250825-976b580c-ced3-448e-93b6-20bbcadfa2b8.png">

**Screenshot 2**
![Screenshot 2022-09-26 at 3 41 22 PM](https://user-images.githubusercontent.com/81156455/192251160-b3fbfc57-3074-4b84-bc0c-07ebe7f79aa1.png)

[Figma Link ](https://www.figma.com/file/1tWUg2fRLIH1AdkjMd0qyr/Dashboard-V2?node-id=2316%3A13218)

**Comment by MamataNivajekar** [comment]
@saieshv The "edit information/loan offers page" is not yet developed.

**Comment by saieshv** [comment]
Do check this issue

**Comment by saieshv** [comment]
can you recheck this, for me, I'm landing on the offers page without any input fields on top

**Comment by saieshv** [comment]
Resolved

**Comment by MamataNivajekar** [comment]
@saieshv fixed
