### ISSUE TITLE
CIBIL Report Page : Pop Up Position

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#20]
Issue : 
repayment Pop Up position is more on the right, and can be kept centered.

<img width="1440" alt="Screenshot 2022-09-26 at 4 08 03 PM" src="https://user-images.githubusercontent.com/81156455/192256440-cd627b5d-ae14-4d76-bd35-bae549b96672.png">

**Comment by MamataNivajekar** [comment]
@saieshv The popup position is horizontally centered as per the design.
