### ISSUE TITLE
CIBIL Alerts Page : Heading to be center aligned 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#22]
Heading "WITH CIBIL ALERTS YOU GET" to be center aligned in the container.
<img width="1126" alt="Screenshot 2022-09-26 at 4 30 50 PM" src="https://user-images.githubusercontent.com/81156455/192260348-3b123953-48c6-48d0-a3d4-a120cd5819a4.png">

**Comment by MamataNivajekar** [comment]
@saieshv The alignment changes are made as per the updated UI

![image](https://user-images.githubusercontent.com/81617777/192268998-bef7a61d-907f-430a-8622-b9c2dff86364.png)
