### ISSUE TITLE
CIBIL Alerts Page : FAQ Section

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#23]
Issue : 
Currently, the link is redirecting to the select plan page, this is to be linked to upgrading plan page

<img width="1102" alt="Screenshot 2022-09-26 at 4 41 05 PM" src="https://user-images.githubusercontent.com/81156455/192262217-b03f1059-cfdb-4d40-ae31-9d99e7d26d30.png">

**Comment by saieshv** [comment]
@MamataNivajekar do recheck this

**Comment by MamataNivajekar** [comment]
@saieshv The link is redirected as per the [doc](https://docs.google.com/document/d/1qpkeZGYUYJsGamSL89JEPJGYCd0Jeeu8/edit?usp=sharing&ouid=102447813605823378074&rtpof=true&sd=true) shared by the client. Please check & let me know.

![image](https://user-images.githubusercontent.com/81617777/195014094-e865747b-5b6a-4274-82d2-efff44273326.png)

**Comment by saieshv** [comment]
Resolved
