### ISSUE TITLE
M: Overview Page - Header Menu Icons

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#30]
Issue : 
Icons For Nav Item  "Repayment Option" & "Score Simulator" looks tempered 

Can be exported from this Figma file 
[Link ](https://www.figma.com/file/1tWUg2fRLIH1AdkjMd0qyr/Dashboard-V2?node-id=5649%3A35115)

<img width="314" alt="Screenshot 2022-09-27 at 11 37 10 AM" src="https://user-images.githubusercontent.com/81156455/192446070-8c8e5739-27aa-44c1-87be-6e7b868ed0c1.png">

**Comment by MamataNivajekar** [comment]
@saieshv I have tried to export the above icons from the Figma design, but they look tempered after export. Can you please share the ".svg" icons for "Repayment Option" & "Score Simulator"?
