### ISSUE TITLE
Footer : Link Missing 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#40]
<img width="1181" alt="Screenshot 2022-10-11 at 10 37 36 AM" src="https://user-images.githubusercontent.com/81156455/195001799-b6c74439-e939-475d-9e8c-8dbdfc1e932c.png">

on some of the footer "Raise a dispute" Link is missing 
Do check for all pages.

**Comment by MamataNivajekar** [comment]
@saieshv updated as per the [doc](https://docs.google.com/document/d/1qpkeZGYUYJsGamSL89JEPJGYCd0Jeeu8/edit?usp=sharing&ouid=102447813605823378074&rtpof=true&sd=true) shared by the client.

![image](https://user-images.githubusercontent.com/81617777/195016495-6836f43b-dfad-41fb-8a0b-a07a00dc3891.png)
