### ISSUE TITLE
Side Nav : Tooltips

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#5]
Issue : 
Currently(example1), the tooltip is shown on the top with white bg which can be kept similar to other tooltips (example 2)
with Fade in & out effect while opening and closing.

**Example 1**
<img width="362" alt="Screenshot 2022-09-26 at 1 20 19 PM" src="https://user-images.githubusercontent.com/81156455/192222162-f1eaa844-8023-4a02-be93-0ca09ab60b4e.png">

**Example 2**
<img width="380" alt="Screenshot 2022-09-26 at 1 22 27 PM" src="https://user-images.githubusercontent.com/81156455/192222590-f98454ae-5657-4460-a72f-ebd851236f3c.png">

**Comment by saieshv** [comment]
@MamataNivajekar some part of the tooltip is getting cropped from the right side
Check this screenshot
![Screenshot 2022-10-10 at 6 27 30 PM](https://user-images.githubusercontent.com/81156455/194871535-6868a758-1403-45c8-b31c-40e78882cada.png)

**Comment by MamataNivajekar** [comment]
@saieshv fixed the above issue, please check in incognito.
