### ISSUE TITLE
My Account Page : Notification Tab - Input Validation

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#52]
Mobile Number & Email "Type" to be added for input validation 

<img width="1066" alt="Screenshot 2022-10-11 at 6 03 58 PM" src="https://user-images.githubusercontent.com/81156455/195091604-40f39599-6fae-4c36-adce-2bd76a7f763e.png">

**Comment by MamataNivajekar** [comment]
@saieshv validation is already added, fill invalid values & try to submit the form

![image](https://user-images.githubusercontent.com/81617777/195102626-3770a276-0959-42d1-9749-e3894ba9ae72.png)
