### ISSUE TITLE
My Account Page : Tick Box 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#54]
<img width="202" alt="Screenshot 2022-10-12 at 12 42 18 PM" src="https://user-images.githubusercontent.com/81156455/195274631-a07e2e52-72a7-4342-9834-e2d305d34599.png">

When Checkboxes are ticked, the current alignment is a little on top. 
This is to be visually balanced, vertically.

**Comment by MamataNivajekar** [comment]
@saieshv fixed
