### ISSUE TITLE
Score Simulator Page : Input Fields Spacing Issue

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#56]
<img width="421" alt="Screenshot 2022-10-12 at 3 02 48 PM" src="https://user-images.githubusercontent.com/81156455/195306791-69e882f8-8e5a-415d-97b8-0f8bbdf153eb.png">

Currently, the spacing is too little between the title and the input fields 
This can be increased manually & visually to be matched with figma ui.

**Comment by MamataNivajekar** [comment]
@saieshv fixed the spacing issue.
