### ISSUE TITLE
M_Loan Offers Page : Pop Up Issue

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#60]
a. The outline on the logo is to be removed

<img width="139" alt="Screenshot 2022-10-12 at 3 41 39 PM" src="https://user-images.githubusercontent.com/81156455/195315915-c7bd1a30-2e56-40db-bacf-5c8e0b5bdd3f.png">

b. Spacing between these 2 elements is to be kept at 20px.

![Screenshot 2022-10-12 at 3 45 41 PM](https://user-images.githubusercontent.com/81156455/195316793-d0dfb56b-446b-4d15-861f-8a24195c4cc7.png)

c. There is an outline of orange bleed around this CTA, this can be removed.

<img width="325" alt="Screenshot 2022-10-12 at 3 46 59 PM" src="https://user-images.githubusercontent.com/81156455/195317068-c092ca13-ebcb-48c9-998a-4e0df608e58c.png">

d. Download Icon looks stretched , and needs to be replaced 
<img width="228" alt="Screenshot 2022-10-12 at 4 29 02 PM" src="https://user-images.githubusercontent.com/81156455/195325806-6b926098-9227-4f6e-bd6d-9eb4241f693e.png">

**Comment by MamataNivajekar** [comment]
@saieshv couldn't replicate the issue -->  c) There is an outline of orange bleed around this CTA, this can be removed.

**Comment by saieshv** [comment]
@MamataNivajekar can you fix this also, spacing between these two elements is 30px. 

<img width="310" alt="Screenshot 2022-10-14 at 10 18 16 AM" src="https://user-images.githubusercontent.com/81156455/195764706-70c1b4f8-f154-4bcb-8f91-a5a2a615d5ae.png">
