### ISSUE TITLE
CIBIL Report Page : Tabs Section

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#72]
There is a 1-2px shift in content(because the text is getting bold on click) while navigating from one tab to another 
also, the transition is instant animation, this can be made in subtle animation same as other transitions on site. 

https://user-images.githubusercontent.com/81156455/195583545-73a563ff-fd01-4492-9fa5-e3062e2a80f7.mov

**Comment by MamataNivajekar** [comment]
@saieshv we can't add a transition for the font weight (regular to bold)

**Comment by saieshv** [comment]
Hi Mamata,
Transition for tabs I meant.
Let me know if we can make the subtle transition on the Underline & that
arrow movement.
