### ISSUE TITLE
Overview Page : Social Score Comparison Section 

### ISSUE THREAD

**Issue by saieshv** [ajency/cibil-dashboard#77]
a. The subheading Text needs to be updated 
to "See how your score compares with other self-monitoring consumers at a specific location."

<img width="1083" alt="Screenshot 2022-10-14 at 11 09 17 AM" src="https://user-images.githubusercontent.com/81156455/195770940-11dbc9a1-ffd7-440c-8401-cb228d7737df.png">

b. Spacing above this section is 65px, this is to be made 60px. 
<img width="1278" alt="Screenshot 2022-10-14 at 11 11 52 AM" src="https://user-images.githubusercontent.com/81156455/195771073-174a95b6-8f1c-4c98-924f-7846d4a9c9e3.png">

c. Also "i" info icon needs to be added here

**Comment by MamataNivajekar** [comment]
@saieshv The subheading text is updated as per the doc.

![image](https://user-images.githubusercontent.com/81617777/195846267-f97fb442-8447-4781-8736-13b7981b15f5.png)

**Comment by MamataNivajekar** [comment]
@saieshv b. Spacing above this section is 65px, this is to be made 60px. --> It's **65px** in the figma design please recheck & confirm.
